python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 10  &> ../../logs/normal_2_True_Austin_SanDiego_0-10.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 10  &> ../../logs/normal_2_True_Austin_SanDiego_1-10.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 10  &> ../../logs/normal_2_True_Austin_SanDiego_2-10.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 10  &> ../../logs/normal_2_True_Austin_SanDiego_3-10.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 10  &> ../../logs/normal_2_True_Austin_SanDiego_4-10.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 20  &> ../../logs/normal_2_True_Austin_SanDiego_0-20.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 20  &> ../../logs/normal_2_True_Austin_SanDiego_1-20.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 20  &> ../../logs/normal_2_True_Austin_SanDiego_2-20.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 20  &> ../../logs/normal_2_True_Austin_SanDiego_3-20.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 20  &> ../../logs/normal_2_True_Austin_SanDiego_4-20.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 30  &> ../../logs/normal_2_True_Austin_SanDiego_0-30.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 30  &> ../../logs/normal_2_True_Austin_SanDiego_1-30.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 30  &> ../../logs/normal_2_True_Austin_SanDiego_2-30.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 30  &> ../../logs/normal_2_True_Austin_SanDiego_3-30.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 30  &> ../../logs/normal_2_True_Austin_SanDiego_4-30.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 40  &> ../../logs/normal_2_True_Austin_SanDiego_0-40.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 40  &> ../../logs/normal_2_True_Austin_SanDiego_1-40.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 40  &> ../../logs/normal_2_True_Austin_SanDiego_2-40.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 40  &> ../../logs/normal_2_True_Austin_SanDiego_3-40.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 40  &> ../../logs/normal_2_True_Austin_SanDiego_4-40.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 50  &> ../../logs/normal_2_True_Austin_SanDiego_0-50.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 50  &> ../../logs/normal_2_True_Austin_SanDiego_1-50.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 50  &> ../../logs/normal_2_True_Austin_SanDiego_2-50.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 50  &> ../../logs/normal_2_True_Austin_SanDiego_3-50.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 50  &> ../../logs/normal_2_True_Austin_SanDiego_4-50.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 60  &> ../../logs/normal_2_True_Austin_SanDiego_0-60.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 60  &> ../../logs/normal_2_True_Austin_SanDiego_1-60.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 60  &> ../../logs/normal_2_True_Austin_SanDiego_2-60.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 60  &> ../../logs/normal_2_True_Austin_SanDiego_3-60.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 60  &> ../../logs/normal_2_True_Austin_SanDiego_4-60.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 70  &> ../../logs/normal_2_True_Austin_SanDiego_0-70.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 70  &> ../../logs/normal_2_True_Austin_SanDiego_1-70.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 70  &> ../../logs/normal_2_True_Austin_SanDiego_2-70.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 70  &> ../../logs/normal_2_True_Austin_SanDiego_3-70.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 70  &> ../../logs/normal_2_True_Austin_SanDiego_4-70.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 80  &> ../../logs/normal_2_True_Austin_SanDiego_0-80.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 80  &> ../../logs/normal_2_True_Austin_SanDiego_1-80.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 80  &> ../../logs/normal_2_True_Austin_SanDiego_2-80.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 80  &> ../../logs/normal_2_True_Austin_SanDiego_3-80.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 80  &> ../../logs/normal_2_True_Austin_SanDiego_4-80.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 90  &> ../../logs/normal_2_True_Austin_SanDiego_0-90.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 90  &> ../../logs/normal_2_True_Austin_SanDiego_1-90.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 90  &> ../../logs/normal_2_True_Austin_SanDiego_2-90.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 90  &> ../../logs/normal_2_True_Austin_SanDiego_3-90.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 90  &> ../../logs/normal_2_True_Austin_SanDiego_4-90.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 0 100  &> ../../logs/normal_2_True_Austin_SanDiego_0-100.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 1 100  &> ../../logs/normal_2_True_Austin_SanDiego_1-100.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 2 100  &> ../../logs/normal_2_True_Austin_SanDiego_2-100.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 3 100  &> ../../logs/normal_2_True_Austin_SanDiego_3-100.out &
python ../../code/graph_laplacian.py normal 2 True Austin SanDiego 4 100  &> ../../logs/normal_2_True_Austin_SanDiego_4-100.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 10  &> ../../logs/transfer_2_True_Austin_SanDiego_0-10.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 10  &> ../../logs/transfer_2_True_Austin_SanDiego_1-10.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 10  &> ../../logs/transfer_2_True_Austin_SanDiego_2-10.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 10  &> ../../logs/transfer_2_True_Austin_SanDiego_3-10.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 10  &> ../../logs/transfer_2_True_Austin_SanDiego_4-10.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 20  &> ../../logs/transfer_2_True_Austin_SanDiego_0-20.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 20  &> ../../logs/transfer_2_True_Austin_SanDiego_1-20.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 20  &> ../../logs/transfer_2_True_Austin_SanDiego_2-20.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 20  &> ../../logs/transfer_2_True_Austin_SanDiego_3-20.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 20  &> ../../logs/transfer_2_True_Austin_SanDiego_4-20.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 30  &> ../../logs/transfer_2_True_Austin_SanDiego_0-30.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 30  &> ../../logs/transfer_2_True_Austin_SanDiego_1-30.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 30  &> ../../logs/transfer_2_True_Austin_SanDiego_2-30.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 30  &> ../../logs/transfer_2_True_Austin_SanDiego_3-30.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 30  &> ../../logs/transfer_2_True_Austin_SanDiego_4-30.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 40  &> ../../logs/transfer_2_True_Austin_SanDiego_0-40.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 40  &> ../../logs/transfer_2_True_Austin_SanDiego_1-40.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 40  &> ../../logs/transfer_2_True_Austin_SanDiego_2-40.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 40  &> ../../logs/transfer_2_True_Austin_SanDiego_3-40.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 40  &> ../../logs/transfer_2_True_Austin_SanDiego_4-40.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 50  &> ../../logs/transfer_2_True_Austin_SanDiego_0-50.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 50  &> ../../logs/transfer_2_True_Austin_SanDiego_1-50.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 50  &> ../../logs/transfer_2_True_Austin_SanDiego_2-50.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 50  &> ../../logs/transfer_2_True_Austin_SanDiego_3-50.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 50  &> ../../logs/transfer_2_True_Austin_SanDiego_4-50.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 60  &> ../../logs/transfer_2_True_Austin_SanDiego_0-60.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 60  &> ../../logs/transfer_2_True_Austin_SanDiego_1-60.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 60  &> ../../logs/transfer_2_True_Austin_SanDiego_2-60.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 60  &> ../../logs/transfer_2_True_Austin_SanDiego_3-60.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 60  &> ../../logs/transfer_2_True_Austin_SanDiego_4-60.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 70  &> ../../logs/transfer_2_True_Austin_SanDiego_0-70.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 70  &> ../../logs/transfer_2_True_Austin_SanDiego_1-70.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 70  &> ../../logs/transfer_2_True_Austin_SanDiego_2-70.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 70  &> ../../logs/transfer_2_True_Austin_SanDiego_3-70.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 70  &> ../../logs/transfer_2_True_Austin_SanDiego_4-70.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 80  &> ../../logs/transfer_2_True_Austin_SanDiego_0-80.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 80  &> ../../logs/transfer_2_True_Austin_SanDiego_1-80.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 80  &> ../../logs/transfer_2_True_Austin_SanDiego_2-80.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 80  &> ../../logs/transfer_2_True_Austin_SanDiego_3-80.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 80  &> ../../logs/transfer_2_True_Austin_SanDiego_4-80.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 90  &> ../../logs/transfer_2_True_Austin_SanDiego_0-90.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 90  &> ../../logs/transfer_2_True_Austin_SanDiego_1-90.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 90  &> ../../logs/transfer_2_True_Austin_SanDiego_2-90.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 90  &> ../../logs/transfer_2_True_Austin_SanDiego_3-90.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 90  &> ../../logs/transfer_2_True_Austin_SanDiego_4-90.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 0 100  &> ../../logs/transfer_2_True_Austin_SanDiego_0-100.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 1 100  &> ../../logs/transfer_2_True_Austin_SanDiego_1-100.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 2 100  &> ../../logs/transfer_2_True_Austin_SanDiego_2-100.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 3 100  &> ../../logs/transfer_2_True_Austin_SanDiego_3-100.out &
python ../../code/graph_laplacian.py transfer 2 True Austin SanDiego 4 100  &> ../../logs/transfer_2_True_Austin_SanDiego_4-100.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 10  &> ../../logs/normal_2_False_Austin_SanDiego_0-10.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 10  &> ../../logs/normal_2_False_Austin_SanDiego_1-10.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 10  &> ../../logs/normal_2_False_Austin_SanDiego_2-10.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 10  &> ../../logs/normal_2_False_Austin_SanDiego_3-10.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 10  &> ../../logs/normal_2_False_Austin_SanDiego_4-10.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 20  &> ../../logs/normal_2_False_Austin_SanDiego_0-20.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 20  &> ../../logs/normal_2_False_Austin_SanDiego_1-20.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 20  &> ../../logs/normal_2_False_Austin_SanDiego_2-20.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 20  &> ../../logs/normal_2_False_Austin_SanDiego_3-20.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 20  &> ../../logs/normal_2_False_Austin_SanDiego_4-20.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 30  &> ../../logs/normal_2_False_Austin_SanDiego_0-30.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 30  &> ../../logs/normal_2_False_Austin_SanDiego_1-30.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 30  &> ../../logs/normal_2_False_Austin_SanDiego_2-30.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 30  &> ../../logs/normal_2_False_Austin_SanDiego_3-30.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 30  &> ../../logs/normal_2_False_Austin_SanDiego_4-30.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 40  &> ../../logs/normal_2_False_Austin_SanDiego_0-40.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 40  &> ../../logs/normal_2_False_Austin_SanDiego_1-40.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 40  &> ../../logs/normal_2_False_Austin_SanDiego_2-40.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 40  &> ../../logs/normal_2_False_Austin_SanDiego_3-40.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 40  &> ../../logs/normal_2_False_Austin_SanDiego_4-40.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 50  &> ../../logs/normal_2_False_Austin_SanDiego_0-50.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 50  &> ../../logs/normal_2_False_Austin_SanDiego_1-50.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 50  &> ../../logs/normal_2_False_Austin_SanDiego_2-50.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 50  &> ../../logs/normal_2_False_Austin_SanDiego_3-50.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 50  &> ../../logs/normal_2_False_Austin_SanDiego_4-50.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 60  &> ../../logs/normal_2_False_Austin_SanDiego_0-60.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 60  &> ../../logs/normal_2_False_Austin_SanDiego_1-60.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 60  &> ../../logs/normal_2_False_Austin_SanDiego_2-60.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 60  &> ../../logs/normal_2_False_Austin_SanDiego_3-60.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 60  &> ../../logs/normal_2_False_Austin_SanDiego_4-60.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 70  &> ../../logs/normal_2_False_Austin_SanDiego_0-70.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 70  &> ../../logs/normal_2_False_Austin_SanDiego_1-70.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 70  &> ../../logs/normal_2_False_Austin_SanDiego_2-70.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 70  &> ../../logs/normal_2_False_Austin_SanDiego_3-70.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 70  &> ../../logs/normal_2_False_Austin_SanDiego_4-70.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 80  &> ../../logs/normal_2_False_Austin_SanDiego_0-80.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 80  &> ../../logs/normal_2_False_Austin_SanDiego_1-80.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 80  &> ../../logs/normal_2_False_Austin_SanDiego_2-80.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 80  &> ../../logs/normal_2_False_Austin_SanDiego_3-80.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 80  &> ../../logs/normal_2_False_Austin_SanDiego_4-80.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 90  &> ../../logs/normal_2_False_Austin_SanDiego_0-90.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 90  &> ../../logs/normal_2_False_Austin_SanDiego_1-90.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 90  &> ../../logs/normal_2_False_Austin_SanDiego_2-90.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 90  &> ../../logs/normal_2_False_Austin_SanDiego_3-90.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 90  &> ../../logs/normal_2_False_Austin_SanDiego_4-90.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 0 100  &> ../../logs/normal_2_False_Austin_SanDiego_0-100.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 1 100  &> ../../logs/normal_2_False_Austin_SanDiego_1-100.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 2 100  &> ../../logs/normal_2_False_Austin_SanDiego_2-100.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 3 100  &> ../../logs/normal_2_False_Austin_SanDiego_3-100.out &
python ../../code/graph_laplacian.py normal 2 False Austin SanDiego 4 100  &> ../../logs/normal_2_False_Austin_SanDiego_4-100.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 10  &> ../../logs/transfer_2_False_Austin_SanDiego_0-10.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 10  &> ../../logs/transfer_2_False_Austin_SanDiego_1-10.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 10  &> ../../logs/transfer_2_False_Austin_SanDiego_2-10.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 10  &> ../../logs/transfer_2_False_Austin_SanDiego_3-10.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 10  &> ../../logs/transfer_2_False_Austin_SanDiego_4-10.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 20  &> ../../logs/transfer_2_False_Austin_SanDiego_0-20.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 20  &> ../../logs/transfer_2_False_Austin_SanDiego_1-20.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 20  &> ../../logs/transfer_2_False_Austin_SanDiego_2-20.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 20  &> ../../logs/transfer_2_False_Austin_SanDiego_3-20.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 20  &> ../../logs/transfer_2_False_Austin_SanDiego_4-20.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 30  &> ../../logs/transfer_2_False_Austin_SanDiego_0-30.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 30  &> ../../logs/transfer_2_False_Austin_SanDiego_1-30.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 30  &> ../../logs/transfer_2_False_Austin_SanDiego_2-30.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 30  &> ../../logs/transfer_2_False_Austin_SanDiego_3-30.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 30  &> ../../logs/transfer_2_False_Austin_SanDiego_4-30.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 40  &> ../../logs/transfer_2_False_Austin_SanDiego_0-40.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 40  &> ../../logs/transfer_2_False_Austin_SanDiego_1-40.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 40  &> ../../logs/transfer_2_False_Austin_SanDiego_2-40.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 40  &> ../../logs/transfer_2_False_Austin_SanDiego_3-40.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 40  &> ../../logs/transfer_2_False_Austin_SanDiego_4-40.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 50  &> ../../logs/transfer_2_False_Austin_SanDiego_0-50.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 50  &> ../../logs/transfer_2_False_Austin_SanDiego_1-50.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 50  &> ../../logs/transfer_2_False_Austin_SanDiego_2-50.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 50  &> ../../logs/transfer_2_False_Austin_SanDiego_3-50.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 50  &> ../../logs/transfer_2_False_Austin_SanDiego_4-50.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 60  &> ../../logs/transfer_2_False_Austin_SanDiego_0-60.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 60  &> ../../logs/transfer_2_False_Austin_SanDiego_1-60.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 60  &> ../../logs/transfer_2_False_Austin_SanDiego_2-60.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 60  &> ../../logs/transfer_2_False_Austin_SanDiego_3-60.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 60  &> ../../logs/transfer_2_False_Austin_SanDiego_4-60.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 70  &> ../../logs/transfer_2_False_Austin_SanDiego_0-70.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 70  &> ../../logs/transfer_2_False_Austin_SanDiego_1-70.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 70  &> ../../logs/transfer_2_False_Austin_SanDiego_2-70.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 70  &> ../../logs/transfer_2_False_Austin_SanDiego_3-70.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 70  &> ../../logs/transfer_2_False_Austin_SanDiego_4-70.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 80  &> ../../logs/transfer_2_False_Austin_SanDiego_0-80.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 80  &> ../../logs/transfer_2_False_Austin_SanDiego_1-80.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 80  &> ../../logs/transfer_2_False_Austin_SanDiego_2-80.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 80  &> ../../logs/transfer_2_False_Austin_SanDiego_3-80.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 80  &> ../../logs/transfer_2_False_Austin_SanDiego_4-80.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 90  &> ../../logs/transfer_2_False_Austin_SanDiego_0-90.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 90  &> ../../logs/transfer_2_False_Austin_SanDiego_1-90.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 90  &> ../../logs/transfer_2_False_Austin_SanDiego_2-90.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 90  &> ../../logs/transfer_2_False_Austin_SanDiego_3-90.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 90  &> ../../logs/transfer_2_False_Austin_SanDiego_4-90.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 0 100  &> ../../logs/transfer_2_False_Austin_SanDiego_0-100.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 1 100  &> ../../logs/transfer_2_False_Austin_SanDiego_1-100.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 2 100  &> ../../logs/transfer_2_False_Austin_SanDiego_2-100.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 3 100  &> ../../logs/transfer_2_False_Austin_SanDiego_3-100.out &
python ../../code/graph_laplacian.py transfer 2 False Austin SanDiego 4 100  &> ../../logs/transfer_2_False_Austin_SanDiego_4-100.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 10  &> ../../logs/normal_4_True_Austin_SanDiego_0-10.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 10  &> ../../logs/normal_4_True_Austin_SanDiego_1-10.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 10  &> ../../logs/normal_4_True_Austin_SanDiego_2-10.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 10  &> ../../logs/normal_4_True_Austin_SanDiego_3-10.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 10  &> ../../logs/normal_4_True_Austin_SanDiego_4-10.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 20  &> ../../logs/normal_4_True_Austin_SanDiego_0-20.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 20  &> ../../logs/normal_4_True_Austin_SanDiego_1-20.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 20  &> ../../logs/normal_4_True_Austin_SanDiego_2-20.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 20  &> ../../logs/normal_4_True_Austin_SanDiego_3-20.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 20  &> ../../logs/normal_4_True_Austin_SanDiego_4-20.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 30  &> ../../logs/normal_4_True_Austin_SanDiego_0-30.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 30  &> ../../logs/normal_4_True_Austin_SanDiego_1-30.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 30  &> ../../logs/normal_4_True_Austin_SanDiego_2-30.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 30  &> ../../logs/normal_4_True_Austin_SanDiego_3-30.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 30  &> ../../logs/normal_4_True_Austin_SanDiego_4-30.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 40  &> ../../logs/normal_4_True_Austin_SanDiego_0-40.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 40  &> ../../logs/normal_4_True_Austin_SanDiego_1-40.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 40  &> ../../logs/normal_4_True_Austin_SanDiego_2-40.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 40  &> ../../logs/normal_4_True_Austin_SanDiego_3-40.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 40  &> ../../logs/normal_4_True_Austin_SanDiego_4-40.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 50  &> ../../logs/normal_4_True_Austin_SanDiego_0-50.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 50  &> ../../logs/normal_4_True_Austin_SanDiego_1-50.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 50  &> ../../logs/normal_4_True_Austin_SanDiego_2-50.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 50  &> ../../logs/normal_4_True_Austin_SanDiego_3-50.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 50  &> ../../logs/normal_4_True_Austin_SanDiego_4-50.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 60  &> ../../logs/normal_4_True_Austin_SanDiego_0-60.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 60  &> ../../logs/normal_4_True_Austin_SanDiego_1-60.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 60  &> ../../logs/normal_4_True_Austin_SanDiego_2-60.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 60  &> ../../logs/normal_4_True_Austin_SanDiego_3-60.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 60  &> ../../logs/normal_4_True_Austin_SanDiego_4-60.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 70  &> ../../logs/normal_4_True_Austin_SanDiego_0-70.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 70  &> ../../logs/normal_4_True_Austin_SanDiego_1-70.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 70  &> ../../logs/normal_4_True_Austin_SanDiego_2-70.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 70  &> ../../logs/normal_4_True_Austin_SanDiego_3-70.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 70  &> ../../logs/normal_4_True_Austin_SanDiego_4-70.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 80  &> ../../logs/normal_4_True_Austin_SanDiego_0-80.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 80  &> ../../logs/normal_4_True_Austin_SanDiego_1-80.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 80  &> ../../logs/normal_4_True_Austin_SanDiego_2-80.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 80  &> ../../logs/normal_4_True_Austin_SanDiego_3-80.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 80  &> ../../logs/normal_4_True_Austin_SanDiego_4-80.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 90  &> ../../logs/normal_4_True_Austin_SanDiego_0-90.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 90  &> ../../logs/normal_4_True_Austin_SanDiego_1-90.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 90  &> ../../logs/normal_4_True_Austin_SanDiego_2-90.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 90  &> ../../logs/normal_4_True_Austin_SanDiego_3-90.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 90  &> ../../logs/normal_4_True_Austin_SanDiego_4-90.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 0 100  &> ../../logs/normal_4_True_Austin_SanDiego_0-100.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 1 100  &> ../../logs/normal_4_True_Austin_SanDiego_1-100.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 2 100  &> ../../logs/normal_4_True_Austin_SanDiego_2-100.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 3 100  &> ../../logs/normal_4_True_Austin_SanDiego_3-100.out &
python ../../code/graph_laplacian.py normal 4 True Austin SanDiego 4 100  &> ../../logs/normal_4_True_Austin_SanDiego_4-100.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 10  &> ../../logs/transfer_4_True_Austin_SanDiego_0-10.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 10  &> ../../logs/transfer_4_True_Austin_SanDiego_1-10.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 10  &> ../../logs/transfer_4_True_Austin_SanDiego_2-10.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 10  &> ../../logs/transfer_4_True_Austin_SanDiego_3-10.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 10  &> ../../logs/transfer_4_True_Austin_SanDiego_4-10.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 20  &> ../../logs/transfer_4_True_Austin_SanDiego_0-20.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 20  &> ../../logs/transfer_4_True_Austin_SanDiego_1-20.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 20  &> ../../logs/transfer_4_True_Austin_SanDiego_2-20.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 20  &> ../../logs/transfer_4_True_Austin_SanDiego_3-20.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 20  &> ../../logs/transfer_4_True_Austin_SanDiego_4-20.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 30  &> ../../logs/transfer_4_True_Austin_SanDiego_0-30.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 30  &> ../../logs/transfer_4_True_Austin_SanDiego_1-30.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 30  &> ../../logs/transfer_4_True_Austin_SanDiego_2-30.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 30  &> ../../logs/transfer_4_True_Austin_SanDiego_3-30.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 30  &> ../../logs/transfer_4_True_Austin_SanDiego_4-30.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 40  &> ../../logs/transfer_4_True_Austin_SanDiego_0-40.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 40  &> ../../logs/transfer_4_True_Austin_SanDiego_1-40.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 40  &> ../../logs/transfer_4_True_Austin_SanDiego_2-40.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 40  &> ../../logs/transfer_4_True_Austin_SanDiego_3-40.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 40  &> ../../logs/transfer_4_True_Austin_SanDiego_4-40.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 50  &> ../../logs/transfer_4_True_Austin_SanDiego_0-50.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 50  &> ../../logs/transfer_4_True_Austin_SanDiego_1-50.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 50  &> ../../logs/transfer_4_True_Austin_SanDiego_2-50.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 50  &> ../../logs/transfer_4_True_Austin_SanDiego_3-50.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 50  &> ../../logs/transfer_4_True_Austin_SanDiego_4-50.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 60  &> ../../logs/transfer_4_True_Austin_SanDiego_0-60.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 60  &> ../../logs/transfer_4_True_Austin_SanDiego_1-60.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 60  &> ../../logs/transfer_4_True_Austin_SanDiego_2-60.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 60  &> ../../logs/transfer_4_True_Austin_SanDiego_3-60.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 60  &> ../../logs/transfer_4_True_Austin_SanDiego_4-60.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 70  &> ../../logs/transfer_4_True_Austin_SanDiego_0-70.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 70  &> ../../logs/transfer_4_True_Austin_SanDiego_1-70.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 70  &> ../../logs/transfer_4_True_Austin_SanDiego_2-70.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 70  &> ../../logs/transfer_4_True_Austin_SanDiego_3-70.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 70  &> ../../logs/transfer_4_True_Austin_SanDiego_4-70.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 80  &> ../../logs/transfer_4_True_Austin_SanDiego_0-80.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 80  &> ../../logs/transfer_4_True_Austin_SanDiego_1-80.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 80  &> ../../logs/transfer_4_True_Austin_SanDiego_2-80.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 80  &> ../../logs/transfer_4_True_Austin_SanDiego_3-80.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 80  &> ../../logs/transfer_4_True_Austin_SanDiego_4-80.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 90  &> ../../logs/transfer_4_True_Austin_SanDiego_0-90.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 90  &> ../../logs/transfer_4_True_Austin_SanDiego_1-90.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 90  &> ../../logs/transfer_4_True_Austin_SanDiego_2-90.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 90  &> ../../logs/transfer_4_True_Austin_SanDiego_3-90.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 90  &> ../../logs/transfer_4_True_Austin_SanDiego_4-90.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 0 100  &> ../../logs/transfer_4_True_Austin_SanDiego_0-100.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 1 100  &> ../../logs/transfer_4_True_Austin_SanDiego_1-100.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 2 100  &> ../../logs/transfer_4_True_Austin_SanDiego_2-100.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 3 100  &> ../../logs/transfer_4_True_Austin_SanDiego_3-100.out &
python ../../code/graph_laplacian.py transfer 4 True Austin SanDiego 4 100  &> ../../logs/transfer_4_True_Austin_SanDiego_4-100.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 10  &> ../../logs/normal_4_False_Austin_SanDiego_0-10.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 10  &> ../../logs/normal_4_False_Austin_SanDiego_1-10.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 10  &> ../../logs/normal_4_False_Austin_SanDiego_2-10.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 10  &> ../../logs/normal_4_False_Austin_SanDiego_3-10.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 10  &> ../../logs/normal_4_False_Austin_SanDiego_4-10.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 20  &> ../../logs/normal_4_False_Austin_SanDiego_0-20.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 20  &> ../../logs/normal_4_False_Austin_SanDiego_1-20.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 20  &> ../../logs/normal_4_False_Austin_SanDiego_2-20.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 20  &> ../../logs/normal_4_False_Austin_SanDiego_3-20.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 20  &> ../../logs/normal_4_False_Austin_SanDiego_4-20.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 30  &> ../../logs/normal_4_False_Austin_SanDiego_0-30.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 30  &> ../../logs/normal_4_False_Austin_SanDiego_1-30.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 30  &> ../../logs/normal_4_False_Austin_SanDiego_2-30.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 30  &> ../../logs/normal_4_False_Austin_SanDiego_3-30.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 30  &> ../../logs/normal_4_False_Austin_SanDiego_4-30.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 40  &> ../../logs/normal_4_False_Austin_SanDiego_0-40.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 40  &> ../../logs/normal_4_False_Austin_SanDiego_1-40.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 40  &> ../../logs/normal_4_False_Austin_SanDiego_2-40.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 40  &> ../../logs/normal_4_False_Austin_SanDiego_3-40.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 40  &> ../../logs/normal_4_False_Austin_SanDiego_4-40.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 50  &> ../../logs/normal_4_False_Austin_SanDiego_0-50.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 50  &> ../../logs/normal_4_False_Austin_SanDiego_1-50.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 50  &> ../../logs/normal_4_False_Austin_SanDiego_2-50.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 50  &> ../../logs/normal_4_False_Austin_SanDiego_3-50.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 50  &> ../../logs/normal_4_False_Austin_SanDiego_4-50.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 60  &> ../../logs/normal_4_False_Austin_SanDiego_0-60.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 60  &> ../../logs/normal_4_False_Austin_SanDiego_1-60.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 60  &> ../../logs/normal_4_False_Austin_SanDiego_2-60.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 60  &> ../../logs/normal_4_False_Austin_SanDiego_3-60.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 60  &> ../../logs/normal_4_False_Austin_SanDiego_4-60.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 70  &> ../../logs/normal_4_False_Austin_SanDiego_0-70.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 70  &> ../../logs/normal_4_False_Austin_SanDiego_1-70.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 70  &> ../../logs/normal_4_False_Austin_SanDiego_2-70.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 70  &> ../../logs/normal_4_False_Austin_SanDiego_3-70.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 70  &> ../../logs/normal_4_False_Austin_SanDiego_4-70.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 80  &> ../../logs/normal_4_False_Austin_SanDiego_0-80.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 80  &> ../../logs/normal_4_False_Austin_SanDiego_1-80.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 80  &> ../../logs/normal_4_False_Austin_SanDiego_2-80.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 80  &> ../../logs/normal_4_False_Austin_SanDiego_3-80.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 80  &> ../../logs/normal_4_False_Austin_SanDiego_4-80.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 90  &> ../../logs/normal_4_False_Austin_SanDiego_0-90.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 90  &> ../../logs/normal_4_False_Austin_SanDiego_1-90.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 90  &> ../../logs/normal_4_False_Austin_SanDiego_2-90.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 90  &> ../../logs/normal_4_False_Austin_SanDiego_3-90.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 90  &> ../../logs/normal_4_False_Austin_SanDiego_4-90.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 0 100  &> ../../logs/normal_4_False_Austin_SanDiego_0-100.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 1 100  &> ../../logs/normal_4_False_Austin_SanDiego_1-100.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 2 100  &> ../../logs/normal_4_False_Austin_SanDiego_2-100.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 3 100  &> ../../logs/normal_4_False_Austin_SanDiego_3-100.out &
python ../../code/graph_laplacian.py normal 4 False Austin SanDiego 4 100  &> ../../logs/normal_4_False_Austin_SanDiego_4-100.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 10  &> ../../logs/transfer_4_False_Austin_SanDiego_0-10.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 10  &> ../../logs/transfer_4_False_Austin_SanDiego_1-10.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 10  &> ../../logs/transfer_4_False_Austin_SanDiego_2-10.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 10  &> ../../logs/transfer_4_False_Austin_SanDiego_3-10.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 10  &> ../../logs/transfer_4_False_Austin_SanDiego_4-10.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 20  &> ../../logs/transfer_4_False_Austin_SanDiego_0-20.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 20  &> ../../logs/transfer_4_False_Austin_SanDiego_1-20.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 20  &> ../../logs/transfer_4_False_Austin_SanDiego_2-20.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 20  &> ../../logs/transfer_4_False_Austin_SanDiego_3-20.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 20  &> ../../logs/transfer_4_False_Austin_SanDiego_4-20.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 30  &> ../../logs/transfer_4_False_Austin_SanDiego_0-30.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 30  &> ../../logs/transfer_4_False_Austin_SanDiego_1-30.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 30  &> ../../logs/transfer_4_False_Austin_SanDiego_2-30.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 30  &> ../../logs/transfer_4_False_Austin_SanDiego_3-30.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 30  &> ../../logs/transfer_4_False_Austin_SanDiego_4-30.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 40  &> ../../logs/transfer_4_False_Austin_SanDiego_0-40.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 40  &> ../../logs/transfer_4_False_Austin_SanDiego_1-40.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 40  &> ../../logs/transfer_4_False_Austin_SanDiego_2-40.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 40  &> ../../logs/transfer_4_False_Austin_SanDiego_3-40.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 40  &> ../../logs/transfer_4_False_Austin_SanDiego_4-40.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 50  &> ../../logs/transfer_4_False_Austin_SanDiego_0-50.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 50  &> ../../logs/transfer_4_False_Austin_SanDiego_1-50.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 50  &> ../../logs/transfer_4_False_Austin_SanDiego_2-50.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 50  &> ../../logs/transfer_4_False_Austin_SanDiego_3-50.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 50  &> ../../logs/transfer_4_False_Austin_SanDiego_4-50.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 60  &> ../../logs/transfer_4_False_Austin_SanDiego_0-60.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 60  &> ../../logs/transfer_4_False_Austin_SanDiego_1-60.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 60  &> ../../logs/transfer_4_False_Austin_SanDiego_2-60.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 60  &> ../../logs/transfer_4_False_Austin_SanDiego_3-60.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 60  &> ../../logs/transfer_4_False_Austin_SanDiego_4-60.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 70  &> ../../logs/transfer_4_False_Austin_SanDiego_0-70.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 70  &> ../../logs/transfer_4_False_Austin_SanDiego_1-70.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 70  &> ../../logs/transfer_4_False_Austin_SanDiego_2-70.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 70  &> ../../logs/transfer_4_False_Austin_SanDiego_3-70.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 70  &> ../../logs/transfer_4_False_Austin_SanDiego_4-70.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 80  &> ../../logs/transfer_4_False_Austin_SanDiego_0-80.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 80  &> ../../logs/transfer_4_False_Austin_SanDiego_1-80.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 80  &> ../../logs/transfer_4_False_Austin_SanDiego_2-80.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 80  &> ../../logs/transfer_4_False_Austin_SanDiego_3-80.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 80  &> ../../logs/transfer_4_False_Austin_SanDiego_4-80.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 90  &> ../../logs/transfer_4_False_Austin_SanDiego_0-90.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 90  &> ../../logs/transfer_4_False_Austin_SanDiego_1-90.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 90  &> ../../logs/transfer_4_False_Austin_SanDiego_2-90.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 90  &> ../../logs/transfer_4_False_Austin_SanDiego_3-90.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 90  &> ../../logs/transfer_4_False_Austin_SanDiego_4-90.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 0 100  &> ../../logs/transfer_4_False_Austin_SanDiego_0-100.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 1 100  &> ../../logs/transfer_4_False_Austin_SanDiego_1-100.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 2 100  &> ../../logs/transfer_4_False_Austin_SanDiego_2-100.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 3 100  &> ../../logs/transfer_4_False_Austin_SanDiego_3-100.out &
python ../../code/graph_laplacian.py transfer 4 False Austin SanDiego 4 100  &> ../../logs/transfer_4_False_Austin_SanDiego_4-100.out &
